
name: CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
          
      - name: Install requirements
        run: |
          cd ./RunningList/server
          pip install -r requirements.txt
        
      - name: Run tests
        run: pytest -v ./RunningList/server

